FROM ubuntu:24.04

ENV DEBIAN_FRONTEND=noninteractive

RUN \
    apt update && \
    apt install -y --no-install-recommends sudo && \
    apt clean && \
    apt autoremove --purge

RUN \
    echo "ubuntu   ALL=(ALL:ALL) NOPASSWD:ALL" | tee /etc/sudoers.d/ubuntu > /dev/null && \
    chmod 440 /etc/sudoers.d/ubuntu

USER ubuntu
WORKDIR /home/ubuntu
